version: '3.8'
services:
  urls-cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - urls-cache:/data
  db:
    image: mongo:latest
    deploy:
      replicas: 1
    ports:
      - '27017:27017'
  api:
    container_name: url-shortener
    build:
        context: ./
    image: url-shortener
    depends_on:
      - db
      - urls-cache
    ports:
      - '8080:8080'
    environment:
      SPRING_DATA_MONGODB_HOST: db
      SPRING_REDIS_HOST: urls-cache
    links:
      - db
      - urls-cache
    volumes:
      - ./:/src

volumes:
  db:
    driver: local
  urls-cache:
    driver: local
